adding followings meta
OpenSourcePolitics/decidim_cards pull request #41
Opened 2022-05-19 13:04 UTC by Fujistone

Link to request : 
https://metabase.osp.cat/model/1504-followings/query

2022-06-03 09:55 UTC, Dynnammo commented
Add meetings

2022-06-09 09:21 UTC, virgile-dev commented on followings/info.yml
> +    select decidim_follows.*, decidim_proposals_proposals.decidim_component_id
add url

2022-06-09 09:24 UTC, virgile-dev commented on followings/info.yml
> +        - users
missing
- budgets 
- initiative

2022-06-09 09:27 UTC, virgile-dev commented on followings/info.yml
> +    select decidim_follows.*, decidim_proposals_proposals.decidim_component_id
and title

2022-08-09 05:58 UTC, Dynnammo commented on followings/info.yml
> +    select decidim_follows.*, decidim_proposals_proposals.decidim_component_id
Done

2022-08-16 12:17 UTC, simonaszilinskas requested changes
corriger le nombre de following - exemple 161
https://demo.decidim.opensourcepolitics.eu/processes/ep/f/115/proposals/161

2022-08-16 12:17 UTC, simonaszilinskas commented
Rajouter le titre (followable_title)

2022-08-31 15:52 UTC, Dynnammo commented
@simonaszilinskas just updated the request here : https://metabase.osp.cat/model/1885-suivis. We can review it whenever you want tomorrow

2022-09-01 13:48 UTC, merged